version: '3'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: rmerces/nginx-reverse
    ports:
      - 80:80
    volumes:
      - nginx-conf:/etc/nginx
      - nginx-cert:/etc/ssl/private

volumes:
  nginx-conf:
  nginx-cert: